#!/bin/sh

create_button() {
	ws="${1:-e}"
	u="${2:-e}"
	o="${3:-e}"
	f="${4:-e}"
	symbol="${5:-e}"
	
	workspace="$2$3$4"
	if [ "$workspace" != "0" ]; then
		echo "(button :onclick \"wmctrl -s $ws\"  :class     \"workspace_$u$o$f\"   \"$symbol\")"
	fi
}

workspaces() {

ws1=0
ws2=1
ws3=2
ws4=3
ws5=4
ws6=5
ws7=6
ws8=7
ws9=8
ws10=9

# Unoccupied
un="0"

# check if Occupied
o1=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws1")
o2=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws2")
o3=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws3")
o4=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws4")
o5=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws5")
o6=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws6")
o7=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws7")
o8=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws8")
o9=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws9")
o10=$(wmctrl -l | awk '{ print $2 }' | grep -wm 1 "$ws10")

# check if Focused
f1=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws1")
f2=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws2")
f3=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws3")
f4=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws4")
f5=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws5")
f6=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws6")
f7=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws7")
f8=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws8")
f9=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws9")
f10=$(xprop -root _NET_CURRENT_DESKTOP | awk '{ print $3 }' | grep "$ws10")

symbol1=""
symbol2=""
symbol3=""
symbol4=""
symbol5=""
symbol6=""
symbol7=""
symbol8="󱞁"
symbol9=""
symbol10=""

echo 	"(box	:class \"works\" :orientation \"v\"	:halign \"center\"	:valign \"start\"	 :space-evenly \"false\" :spacing \"-5\" $(create_button "$ws1" "$un" "$o1" "$f1" "$symbol1") $(create_button "$ws2" "$un" "$o2" "$f2" "$symbol2") $(create_button "$ws3" "$un" "$o3" "$f3" "$symbol3") $(create_button "$ws4" "$un" "$o4" "$f4" "$symbol4") $(create_button "$ws5" "$un" "$o5" "$f5" "$symbol5") $(create_button "$ws6" "$un" "$o6" "$f6" "$symbol6") $(create_button "$ws7" "$un" "$o7" "$f7" "$symbol7") $(create_button "$ws8" "$un" "$o8" "$f8" "$symbol8") $(create_button "$ws9" "$un" "$o9" "$f9" "$symbol9") $(create_button "$ws10" "$un" "$o10" "$f10" "$symbol10"))"
}

workspaces
xprop -spy -root _NET_CURRENT_DESKTOP | while read -r _ ; do
	workspaces
done
